version: 2

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused

linters-settings:
  gocyclo:
    min-complexity: 20

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
